name: Deployment 1 v2
on: push
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

  install-dependencies:
    needs: checkout-job
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci

  Lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: npm run lint
  Test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: npm test

  Deploy:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        run: npm run build
