name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello world\n"
          echo "Hi just testing multiline of code\n"
          echo "Looks like its working"
      - name: print goodbye
        run: echo "Goodbye world"
